CREATE SEQUENCE SYSTEM_SEQUENCE_D2481274_D0FF_4648_B2F0_8F2E0D1A05D9;

CREATE TABLE SAVEDCHAT_NEW
(
  CHAT_ID   BIGINT PRIMARY KEY NOT NULL,
  LATITUDE  DOUBLE             NOT NULL,
  LONGITUDE DOUBLE             NOT NULL,
  ISADMIN   BOOLEAN            NOT NULL,
  STEP      VARCHAR(255)
);

INSERT INTO SAVEDCHAT_NEW (CHAT_ID, LATITUDE, LONGITUDE, ISADMIN, STEP)
  SELECT
    CHATID,
    LATITUDE,
    LONGITUDE,
    ISADMIN,
    STEP
  FROM SAVEDCHAT;

DROP TABLE SAVEDCHAT;

ALTER TABLE SAVEDCHAT_NEW
  RENAME TO SAVEDCHAT;

CREATE TABLE USERALERT
(
  ID       BIGINT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_D2481274_D0FF_4648_B2F0_8F2E0D1A05D9) AUTO_INCREMENT PRIMARY KEY NOT NULL,
  CHAT_ID  BIGINT,
  DELAY    BIGINT                                                                                                                 NOT NULL,
  TIMETYPE VARCHAR(255),
  CONSTRAINT FK4L1KF9KG517UXYV34GMC5VEYP FOREIGN KEY (CHAT_ID) REFERENCES SAVEDCHAT (CHAT_ID)
);
